import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import styles from '../styles/home.module.css';
import { Header, PollCard, SearchBar } from '../components';

interface IProps {
	data: Array<any>;
}

const Home: NextPage<IProps> = ({ data }) => {
	const [polls, setPolls] = useState<
		{
			title: string;
			user: string;
			createdAt: Date;
			tags: string[];
			votes: number;
		}[]
	>([]);

	useEffect(() => {
		const pollNumber = Math.floor(Math.random() * 5) + 1;
		const temp = [];
		for (let i = 0; i < pollNumber; i++) {
			const ranText = Math.floor(Math.random() * data.length);

			temp.push({
				title: data[ranText].title,
				user: 'Anonymous',
				createdAt: data[ranText].createdAt,
				tags: data[ranText].tags,
				description: data[ranText].description,
				votes: data[ranText].votes,
			});
		}

		setPolls(temp);
	}, []);

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />

			<main className={styles.main}>
				<SearchBar />

				{/* <h1>Global polls</h1> */}

				<div className={styles.grid}>
					{polls.map((x, i) => (
						<PollCard key={i} cardInfo={x} />
					))}
				</div>
			</main>
		</div>
	);
};

export const getServerSideProps = async () => {
	const resTags = await fetch('https://api.fake-rest.refine.dev/tags');
	const jsonTags = await resTags.json();

	const res = await fetch('https://api.fake-rest.refine.dev/posts');
	const json = (await res.json()).slice(0, 50);

	return {
		props: {
			data: json.map((x: any) => ({
				title: x.title,
				tags: x.tags.map(
					(y: any) => jsonTags.find((z: any) => z.id === y).title
				),
				createdAt: x.createdAt,
				description: x.content,
				votes: x.hit,
			})),
		},
	};
};

export default Home;
